### ISSUE TITLE
Is this usable in 2020?

### ISSUE THREAD

**Issue by 619** [marcelklehr/gulf#39]
I have been trying to implement two way editing with contentEditable for 2 days with no success. Given how unclear and incomplete the documentation is, would it be more time effective to just build on top of mutation-summary?

**Comment by marcelklehr** [comment]
Hello @619 
I'm happy that you are interested in this library. Unfortunately my work on OT came to halt a few years ago and I didn't have the need to maintain this library anymore, which is why I haven't. It has worked splendidly in the past, however, and it saddens me to see it lie dormant like this. It probably needs an update to work smoothly again, though.

**Comment by 619** [comment]
I think it still works, however the quality of the documentation has not been sufficient for me to successfully implement a working version with minor tweaks. Mutation-Summary was written like 6 years ago and I got that working fine with a few minor bug fixes.

**Comment by marcelklehr** [comment]
Do you want to join me over at gitter? https://gitter.im/marcelklehr/gulf
